name = "go-website"
main = "./build/worker.mjs"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "make build"
watch_dir = ["ui/**/*.templ", "main.go", "assets/css/input.css"]

[env.production]
vars = { GO_ENV = "production" }

[env.development]
vars = { GO_ENV = "development" }